### ISSUE TITLE
Dear kwea123

### ISSUE THREAD

**Issue by MAILAB-Yonsei** [kwea123/kwea123#10]
I'm really really appreciate to you for your implementations of NeRF, NeRF-w, and NSSF. Hope you become one of the best pioneers in this field.

**Comment by kwea123** [comment]
Thank you! Hope you have a good experience using my code! Yes, other than these re-implementations, I also do research in this field and plan to publish some papers in the near future. Thanks for your encouragement!

**Comment by SSground** [comment]
> Thank you! Hope you have a good experience using my code! Yes, other than these re-implementations, I also do research in this field and plan to publish some papers in the near future. Thanks for your encouragement!

I sent an email to this mailbox and never got a response
