### ISSUE TITLE
Resources for implementing custom CUDA kernels.

### ISSUE THREAD

**Issue by SrinjaySarkar** [kwea123/kwea123#17]
Hi, thanks for all your implementations. It has made implementing my experiments much easier and faster. Do you have some pointers and/or resources  for learning C++/CUDA for implementing custom CUDA kernels for various tasks specifically for 3D vision and using them as a Pytorch extension?  Not be too specific but something like [this](https://github.com/POSTECH-CVLab/point-transformer/search?l=cuda) or [this](https://github.com/dvlab-research/VFF/search?l=cuda). I will really appreciate your help.

**Comment by kwea123** [comment]
Hi, I will do some basic tutorial videos (chinese with english subtitle) soon, thanks for the patience! I learn mostly from pytorch official code and qiita (japanese site) so I'm not sure it helps...

[this](https://qiita.com/windfall/items/5e4daa5f400d599c3c32#%E5%A4%89%E6%95%B0%E3%81%8Ccontiguous%E3%81%98%E3%82%83%E3%81%AA%E3%81%84%E3%81%A8%E3%81%84%E3%81%86%E3%82%A8%E3%83%A9%E3%83%BCruntimeerror-tensor-must-be-contiguous-%E3%81%8C%E5%87%BA%E3%81%9F)
