### ISSUE TITLE
About sponsor

### ISSUE THREAD

**Issue by maoqingyu1996** [kwea123/kwea123#18]
Hello, friends from Taiwan. I read a lot of your content and YouTuber videos about coordinate-MLPs. I want to be your sponsor but I don't have a credit card and the PayPal link fails. I suggest you to add a QR code or other methods about WeChat payment or Alipay, it will be easier for people from mainland China to sponsor you. Wishing you a great day!

**Comment by kwea123** [comment]
Hi, thanks for your suggestion! Unfortunately I don't have wechat so I cannot setup an account... I updated my paypal link: https://paypal.me/kwea123

Thanks for your sponsorship! I will work my best!

**Comment by maoqingyu1996** [comment]
Maybe you can register an Alipay account with your mobile phone number



At 2022-06-18 21:15:10, "AI葵" ***@***.***> wrote:

Hi, thanks for your suggestion! Unfortunately I don't have wechat so I cannot setup an account... I updated my paypal link: https://paypal.me/kwea123

Thanks for your sponsorship! I will work my best!
