### ISSUE TITLE
Lightning App

### ISSUE THREAD

**Issue by tchaton** [kwea123/kwea123#19]
Hey there,

Awesome work with instant-ngp. I am part of the PyTorch Lightning Core Team.

We recently released a new framework to transform those kind of project into ML product on lightning.ai with potential users.

I was actually planning to do what you did, so you saved me time 😁

I wondered if you would like to collaborate on making this an app ?

If you are interested, join PyTorch Lightning Slack and ping me, my username is tchaton.

**Comment by kwea123** [comment]
I'm interested, will ping you in slack!
