### ISSUE TITLE
您好，有个库的问题想问您

### ISSUE THREAD

**Issue by WolfHolo2333** [kwea123/kwea123#29]
我这里在跑一个nerf相关方法的对比实验 他环境里说是要安装vren库
但我并没有找到这个库 但我在您的一个项目里看到import vren这一步 在您那个项目[ngp_pl](https://github.com/kwea123/ngp_pl)的models/csrc下有相关安装代码
我想问一下这个库的完整全称是什么 万分感谢您！

**Comment by kwea123** [comment]
這是我自己寫的，他的內容就是models/csrc裡的東西
透過`pip install models/csrc/` 就可以安裝
